---
- hosts: localhost
  name: Create Access EVPL UNI 6x
  connection: local
  gather_facts: false
  vars:
    service_name: Service-TEST1
    A_UNI_NODE: CE-1
    A_UNI_PORT: 1
    Z_UNI_NODE: CE-2
    Z_UNI_PORT: 1
    SVID: 1000
  tasks:
    - name: ------------------- BOOTSTRAP -------------------
      ansible.builtin.include_tasks: tasks/bootstrap.yml
    - name: ------------------- CREATE L2 Facade -------------------
      ansible.builtin.include_tasks: tasks/create_resource.yml
      vars:
        body: '{{ lookup("template", "templates/EPL.yml.j2") }}'
        store_name: "{{ service_name }}"
