---
- hosts: localhost
  name: Create Access EVPL UNI 6x
  connection: local
  gather_facts: false
  roles:
    - bootstrap
  vars:
    service_name: Service-TEST1
    A_UNI_NODE: CE-1
    A_UNI_PORT: 1
    Z_UNI_NODE: CE-2
    Z_UNI_PORT: 1
    SVID: 1000
  tasks:
    - name: ------------------- CREATE L2 Facade -------------------
      ansible.builtin.include_tasks: tasks/create_resource.yml
      vars:
        body: '{{ lookup("template", "templates/EPL.yml.j2") }}'
        store_name: "{{ service_name }}"
    - name: ------------------- GET Service Facade Intent Relationship -------------------
      ansible.builtin.include_tasks: tasks/get_relationship_0_targetId(sourceId).yml
      vars:
        sourceId: "{{ resource.id }}"
    - name: ------------------- Await Service Intent active -------------------
      ansible.builtin.include_tasks: tasks/await_resource_orchstate(resourceId,orchState).yml
      vars:
        resourceId: "{{ targetId }}"
        orchState: active
    - name: ------------------- Await Service Intent COMPLETE_FULLY_READY -------------------
      ansible.builtin.include_tasks: tasks/await_resource_deploymentState(resourceId,state).yml
      vars:
        resourceId: "{{ targetId }}"
        state: COMPLETE_FULLY_READY
        store_name: Intent
