---
- hosts: localhost
  name: Create Access EVPL UNI 6x
  connection: local
  gather_facts: false
  vars:
    service_name: Service TEST1
    A_UNI_NODE: CE-1
    A_UNI_PORT: 1
    Z_UNI_NODE: CE-2
    Z_UNI_PORT: 1
  tasks:
    - name: ------------------- BOOTSTRAP -------------------
      ansible.builtin.import_tasks: tasks/bootstrap.yml
    - name: ------------------- CREATE L2 Facade -------------------
      ansible.builtin.import_tasks: tasks/create_resource.yml
      # returns resource fact
      vars:
        body: '{{ lookup("template", "templates/EPL.yml.j2") }}'
    - name: Store Created resource ID
      ansible.builtin.set_fact:
        L2_FACADE: "{{ resource }}"
    - ansible.builtin.debug:
        var: L2_FACADE
