---
- hosts: localhost
  name: Get Service
  connection: local
  gather_facts: false
  roles:
    - bootstrap
  vars:
    resourceId: 656ae940-ed98-11ec-b52d-d3fadccc22d3
  tasks:
    - name: ------------------- GET Service Intent Facade Resource -------------------
      ansible.builtin.include_tasks: tasks/get_resource(resourceId).yml
      vars:
        store_name: Facade
    - name: ------------------- DELETE Service Intent Facade Resource -------------------
      ansible.builtin.include_tasks: tasks/delete_resource(resourceId).yml
