---
- hosts: localhost
  name: Get Service
  connection: local
  gather_facts: false
  roles:
    - bootstrap
  vars:
    resourceId: "{{ store['Service-TEST1'].id }}"
  tasks:
    - name: ------------------- DELETE Service Intent Facade Resource -------------------
      ansible.builtin.include_tasks: tasks/delete_resource(resourceId).yml
