---
- hosts: localhost
  name: Print Vars
  connection: local
  gather_facts: false
  roles:
    - bootstrap
  tasks:
    - name: Print products_by_resourceType
      ansible.builtin.debug:
        var: products_by_resourceType
