- name: Awaiting {{ resourceId }} active
  register: result
  uri:
    url: "https://{{ mcp }}/bpocore/market/api/v1/resources/{{ resourceId }}"
    method: GET
    validate_certs: no
    headers:
      Content-Type: "application/json"
      Authorization: "bearer {{ token }}"
  until: result.json.orchState == orchState
  retries: 30
  delay: 2

- name: store resource result
  set_fact:
    resource: "{{ result.json }}"
    cacheable: yes

- name: Store
  ansible.builtin.set_fact:
    store: "{{ store | default({}) | combine({store_name: resource}) }}"
    cacheable: yes
  when: store_name
- name: store resource result
  set_fact:
    store_name: null
