---
- name: Waiting for resource operation to complete
  register: result
  uri:
    url: "https://{{ mcp }}/bpocore/market/api/v1/resources/{{ resourceId }}/operations/{{ operationId }}"
    method: GET
    validate_certs: no
    headers:
      Content-Type: "application/json"
      Authorization: "bearer {{ token }}"
  until: result.json.state == "successful"
  retries: 30
  delay: 2
- name: store operation result
  set_fact:
    operation: "{{ result.json }}"
    cacheable: yes
- name: Print operation
  ansible.builtin.debug:
    var: operation
