---
- name: Creating Resource
  register: result
  uri:
    url: "https://{{ mcp }}/bpocore/market/api/v1/resources"
    method: POST
    status_code: 201
    body_format: json
    validate_certs: no
    headers:
      Content-Type: "application/json"
      Authorization: "bearer {{ token }}"
    body: "{{ body | from_yaml | to_json }}"
- name: Awaiting {{ resource_id }} active
  register: result
  uri:
    url: "https://{{ mcp }}/bpocore/market/api/v1/resources/{{ resource_id }}"
    method: GET
    validate_certs: no
    headers:
      Content-Type: "application/json"
      Authorization: "bearer {{ token }}"
  until: result.json.orchState == "active"
  retries: 30
  delay: 2
- name: store resource result
  set_fact:
    resource: "{{ result.json }}"
    cacheable: yes
