---
- name: capture token
  when: token is not defined
  block:
    - name: Get Token
      uri:
        url: "https://{{ mcp }}/tron/api/v1/oauth2/tokens"
        method: POST
        body: "username=admin&password=adminpw&grant_type=password"
        headers:
          accept: "application/json"
        validate_certs: no
      register: result
    - name: Store the response from login call as token
      set_fact:
        token: "{{ result.json.accessToken }}"
        token_set: anything

- name: Store token
  when: token_set is defined
  block:
    - name: Open vars file
      slurp:
        path: vars.yml
      register: r_myfile
    - name: Read yaml to dictionary
      set_fact:
        mydata: "{{ r_myfile['content'] | b64decode | from_yaml }}"
    - name: Patch yaml dictionary
      set_fact:
        mydata: "{{ mydata | combine(newdata, recursive=True) }}"
      vars: 
        newdata:
          token: "{{ token }}"
    - name: Write yaml file
      copy:
        content: '{{ mydata | to_nice_yaml }}'
        dest: vars.yml
