- name: Waiting for resource operation to complete
  register: result
  uri:
    url: "https://{{ mcp }}/bpocore/market/api/v1/resources/{{ resourceId }}/operations"
    method: GET
    validate_certs: no
    headers:
      Content-Type: "application/json"
      Authorization: "bearer {{ token }}"
- name: store operation result
  set_fact:
    operations: "{{ result.json }}"
- name: Print operation
  ansible.builtin.debug:
    var: operations
    verbosity: 1
