- name: Getting resource {{ resourceId }}
  register: result
  uri:
    url: "https://{{ mcp }}/bpocore/market/api/v1/resources/{{ resourceId }}"
    method: GET
    validate_certs: no
    headers:
      Content-Type: "application/json"
      Authorization: "bearer {{ token }}"
- name: store resource result
  set_fact:
    resource: "{{ result.json }}"
- name: Print resource
  ansible.builtin.debug:
    var: resource
    verbosity: 1
- name: Store
  ansible.builtin.set_fact:
    store: "{{ store | default({}) | combine({store_name: resource}) }}"
    cacheable: yes
  when: store_name is defined and store_name
- name: store resource result
  set_fact:
    store_name: null
