- name: Getting relationships {{ sourceId }} active
  register: result
  uri:
    url: "https://{{ mcp }}/bpocore/market/api/v1/relationships?q=sourceId:{{ sourceId }}"
    method: GET
    validate_certs: no
    headers:
      Content-Type: "application/json"
      Authorization: "bearer {{ token }}"
- name: Set response fact
  set_fact:
    relationships: "{{ result.json['items'] }}"
- name: Print relationships
  debug:
    var: relationships
    verbosity: 1
- name: Set response fact
  set_fact:
    targetId: "{{ relationships[0].targetId }}"
- name: Print targetId
  debug:
    var: targetId
    verbosity: 1
